import 'dart:convert';
import 'dart:io';

const String _generatedLockfileHeader = '# Generated by pub';
const Set<String> _requiredMetadataPlatforms = <String>{
  'android',
  'ios',
  'root',
};
const Set<String> _requiredUnmanagedFiles = <String>{
  'ios/Runner.xcodeproj/project.pbxproj',
  'lib/main.dart',
};
final RegExp _revisionPattern = RegExp(r'^[0-9a-fA-F]{40}$');

/// 校验需要提交的 Flutter 生成产物是否与输入及工程边界一致。
///
/// [lockfileBefore] 是执行受约束的 `flutter pub get` 前读取的锁文件，
/// [lockfileAfter] 是命令成功后的内容。两者必须逐字节相同，且锁文件必须保留
/// pub 的生成标记。[metadataContent] 必须保留 Flutter 应用类型、仅 Android/iOS
/// 的平台集合、合法迁移 revision，以及已定制入口和 PBX 文件的保护项。
///
/// `.metadata` 顶层 revision 记录项目创建时的 Flutter framework，不是当前 SDK
/// pin，因此 SDK 升级后也不应与运行中的 Flutter 版本比较。当前工具链的
/// 完整 revision 由 CI workflow 独立校验。
///
/// 返回值经过排序且不包含原始配置内容，便于 CI 稳定输出并避免把本机信息带入日志。
List<String> validateGeneratedFiles({
  required List<int> lockfileBefore,
  required List<int> lockfileAfter,
  required String metadataContent,
}) {
  final List<String> violations = <String>[];
  final String? lockfileText = _decodeLockfile(lockfileBefore);
  if (lockfileText == null ||
      !lockfileText.startsWith(_generatedLockfileHeader)) {
    violations.add('[GENERATED_LOCK_HEADER] pubspec.lock 缺少 pub 生成标记。');
  }
  if (!_sameBytes(lockfileBefore, lockfileAfter)) {
    violations.add('[GENERATED_LOCK_STALE] 受约束的 pub get 改写了 pubspec.lock。');
  }

  _validateMetadata(metadataContent, violations);

  violations.sort();
  return violations;
}

/// 执行生成产物新鲜度检查。
///
/// CLI 把 `pubspec.yaml` 与 `pubspec.lock` 复制到隔离临时目录，再执行
/// `flutter pub get --enforce-lockfile` 并逐字节比较结果。这样能够识别 pub 只更新
/// SDK 区间等不会触发命令失败的漂移，也不会让检查过程改写仓库证据。可选参数
/// `--root <path>` 用于 CI 或外部调用。
Future<void> main(List<String> arguments) async {
  late final Directory projectRoot;
  try {
    projectRoot = _resolveProjectRoot(arguments);
  } on FormatException catch (error) {
    stderr.writeln('生成产物检查参数错误：${error.message}');
    stderr.writeln(
      '用法：dart tool/ci/check_generated_files.dart [--root <path>]',
    );
    exitCode = 64;
    return;
  }

  final File lockfile = File(
    '${projectRoot.path}${Platform.pathSeparator}pubspec.lock',
  );
  final File pubspec = File(
    '${projectRoot.path}${Platform.pathSeparator}pubspec.yaml',
  );
  final File metadata = File(
    '${projectRoot.path}${Platform.pathSeparator}.metadata',
  );
  if (!_isRegularFile(pubspec) ||
      !_isRegularFile(lockfile) ||
      !_isRegularFile(metadata)) {
    stderr.writeln('生成产物检查失败：缺少 pubspec.yaml、pubspec.lock 或 .metadata。');
    exitCode = 1;
    return;
  }

  final List<int> lockfileBefore = lockfile.readAsBytesSync();
  late final List<int> regeneratedLockfile;
  try {
    regeneratedLockfile = await _regenerateLockfile(
      pubspec: pubspec,
      lockfile: lockfile,
    );
  } on _ProcessFailedException catch (error) {
    _writeProcessFailure(command: error.command, result: error.result);
    exitCode = 1;
    return;
  } on ProcessException catch (error) {
    stderr.writeln('生成产物检查失败：无法执行 Flutter（${error.message}）。');
    exitCode = 1;
    return;
  } on FileSystemException catch (error) {
    stderr.writeln('生成产物检查失败：无法准备或清理隔离目录（${error.message}）。');
    exitCode = 1;
    return;
  }

  final List<String> violations = validateGeneratedFiles(
    lockfileBefore: lockfileBefore,
    lockfileAfter: regeneratedLockfile,
    metadataContent: metadata.readAsStringSync(),
  );
  if (violations.isNotEmpty) {
    stderr.writeln('生成产物新鲜度检查失败，共 ${violations.length} 项：');
    for (final String violation in violations) {
      stderr.writeln('- $violation');
    }
    exitCode = 1;
    return;
  }

  stdout.writeln('生成产物新鲜度检查通过：pubspec.lock 与 .metadata 均有效。');
}

Future<List<int>> _regenerateLockfile({
  required File pubspec,
  required File lockfile,
}) async {
  final Directory temporaryDirectory = Directory.systemTemp.createTempSync(
    'flutter-template-lock-check-',
  );
  try {
    File(
      '${temporaryDirectory.path}${Platform.pathSeparator}pubspec.yaml',
    ).writeAsBytesSync(pubspec.readAsBytesSync(), flush: true);
    final File temporaryLockfile = File(
      '${temporaryDirectory.path}${Platform.pathSeparator}pubspec.lock',
    );
    temporaryLockfile.writeAsBytesSync(lockfile.readAsBytesSync(), flush: true);

    final ProcessResult result = await Process.run(
      'flutter',
      <String>['pub', 'get', '--enforce-lockfile'],
      workingDirectory: temporaryDirectory.path,
      runInShell: Platform.isWindows,
    );
    if (result.exitCode != 0) {
      throw _ProcessFailedException(
        command: 'flutter pub get --enforce-lockfile',
        result: result,
      );
    }
    return temporaryLockfile.readAsBytesSync();
  } finally {
    // 临时目录由本函数创建且只含公开 pub 输入；精确删除避免在系统临时目录遗留副本。
    temporaryDirectory.deleteSync(recursive: true);
  }
}

String? _decodeLockfile(List<int> bytes) {
  try {
    return utf8.decode(bytes);
  } on FormatException {
    return null;
  }
}

void _validateMetadata(String content, List<String> violations) {
  String? versionRevision;
  String? versionChannel;
  String? projectType;
  bool insideVersion = false;
  bool insideMigrationPlatforms = false;
  bool insideUnmanagedFiles = false;
  String? currentPlatform;
  final Map<String, _MetadataPlatformRevisions> platforms =
      <String, _MetadataPlatformRevisions>{};
  final Set<String> duplicatePlatforms = <String>{};
  final Set<String> unmanagedFiles = <String>{};

  for (final String line in const LineSplitter().convert(content)) {
    if (line == 'version:') {
      insideVersion = true;
      insideMigrationPlatforms = false;
      insideUnmanagedFiles = false;
      currentPlatform = null;
      continue;
    }
    if (line.startsWith('project_type:')) {
      insideVersion = false;
      projectType = _readYamlScalar(line.substring('project_type:'.length));
      continue;
    }
    if (line == 'migration:') {
      insideVersion = false;
      continue;
    }
    if (line == '  platforms:') {
      insideMigrationPlatforms = true;
      insideUnmanagedFiles = false;
      currentPlatform = null;
      continue;
    }
    if (line == '  unmanaged_files:') {
      insideMigrationPlatforms = false;
      insideUnmanagedFiles = true;
      currentPlatform = null;
      continue;
    }
    if (line.isNotEmpty && !line.startsWith(' ')) {
      insideVersion = false;
      insideMigrationPlatforms = false;
      insideUnmanagedFiles = false;
      currentPlatform = null;
      continue;
    }

    if (insideVersion) {
      if (line.startsWith('  revision:')) {
        versionRevision = _readYamlScalar(line.substring('  revision:'.length));
      } else if (line.startsWith('  channel:')) {
        versionChannel = _readYamlScalar(line.substring('  channel:'.length));
      }
      continue;
    }

    if (insideMigrationPlatforms) {
      if (line.startsWith('    - platform:')) {
        currentPlatform = _readYamlScalar(
          line.substring('    - platform:'.length),
        );
        if (currentPlatform == null || currentPlatform.isEmpty) {
          currentPlatform = null;
          continue;
        }
        if (platforms.containsKey(currentPlatform)) {
          duplicatePlatforms.add(currentPlatform);
        }
        platforms.putIfAbsent(currentPlatform, _MetadataPlatformRevisions.new);
      } else if (currentPlatform != null &&
          line.startsWith('      create_revision:')) {
        platforms[currentPlatform]!.createRevision = _readYamlScalar(
          line.substring('      create_revision:'.length),
        );
      } else if (currentPlatform != null &&
          line.startsWith('      base_revision:')) {
        platforms[currentPlatform]!.baseRevision = _readYamlScalar(
          line.substring('      base_revision:'.length),
        );
      }
      continue;
    }

    if (insideUnmanagedFiles && line.startsWith('    - ')) {
      final String? path = _readYamlScalar(line.substring('    - '.length));
      if (path != null && path.isNotEmpty) {
        unmanagedFiles.add(path);
      }
    }
  }

  if (versionRevision == null || !_revisionPattern.hasMatch(versionRevision)) {
    violations.add('[GENERATED_METADATA_REVISION] .metadata 缺少合法的创建 revision。');
  }
  if (versionChannel != 'stable') {
    violations.add('[GENERATED_METADATA_CHANNEL] .metadata 必须记录 stable 创建频道。');
  }
  if (projectType != 'app') {
    violations.add(
      '[GENERATED_METADATA_PROJECT_TYPE] .metadata 必须记录 app 项目类型。',
    );
  }
  if (duplicatePlatforms.isNotEmpty ||
      !_sameStringSet(platforms.keys.toSet(), _requiredMetadataPlatforms)) {
    violations.add(
      '[GENERATED_METADATA_PLATFORMS] .metadata 必须且只能登记 root、Android 和 iOS。',
    );
  }
  if (platforms.values.any(
    (_MetadataPlatformRevisions revisions) =>
        revisions.createRevision == null ||
        !_revisionPattern.hasMatch(revisions.createRevision!) ||
        revisions.baseRevision == null ||
        !_revisionPattern.hasMatch(revisions.baseRevision!),
  )) {
    violations.add(
      '[GENERATED_METADATA_PLATFORM_REVISION] .metadata 平台迁移 revision 无效。',
    );
  }
  if (!unmanagedFiles.containsAll(_requiredUnmanagedFiles)) {
    violations.add('[GENERATED_METADATA_UNMANAGED] .metadata 缺少定制入口或 PBX 保护项。');
  }
}

String? _readYamlScalar(String source) {
  final String value = source.trim();
  if (value.isEmpty) {
    return null;
  }
  if (value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'")))) {
    return value.substring(1, value.length - 1);
  }
  return value;
}

bool _sameStringSet(Set<String> left, Set<String> right) {
  return left.length == right.length && left.containsAll(right);
}

bool _sameBytes(List<int> left, List<int> right) {
  if (left.length != right.length) {
    return false;
  }
  for (int index = 0; index < left.length; index += 1) {
    if (left[index] != right[index]) {
      return false;
    }
  }
  return true;
}

void _writeProcessFailure({
  required String command,
  required ProcessResult result,
}) {
  stderr.writeln('生成产物检查失败：`$command` 返回 ${result.exitCode}。');
  final String standardError = result.stderr.toString().trim();
  if (standardError.isNotEmpty) {
    stderr.writeln(standardError);
  }
}

Directory _resolveProjectRoot(List<String> arguments) {
  if (arguments.isEmpty) {
    return Directory.current.absolute;
  }
  if (arguments.length == 2 && arguments.first == '--root') {
    return Directory(arguments[1]).absolute;
  }
  throw const FormatException('只支持可选参数 `--root <path>`。');
}

bool _isRegularFile(File file) {
  return FileSystemEntity.typeSync(file.path, followLinks: false) ==
      FileSystemEntityType.file;
}

class _ProcessFailedException implements Exception {
  const _ProcessFailedException({required this.command, required this.result});

  final String command;
  final ProcessResult result;
}

class _MetadataPlatformRevisions {
  String? createRevision;
  String? baseRevision;
}
