import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';

import '../../../tool/ci/check_generated_files.dart';

const String _revision = '35c388afb57ef061d06a39b537336c87e0e3d1b1';

void main() {
  group('validateGeneratedFiles', () {
    test(
      'accepts an unchanged generated lockfile and valid creation metadata',
      () {
        final List<int> lockfile = utf8.encode(
          '# Generated by pub\npackages:\n',
        );

        final List<String> violations = validateGeneratedFiles(
          lockfileBefore: lockfile,
          lockfileAfter: List<int>.of(lockfile),
          metadataContent: _validMetadata(_revision),
        );

        expect(violations, isEmpty);
      },
    );

    test('accepts metadata that records an older creation SDK', () {
      final List<int> lockfile = utf8.encode('# Generated by pub\npackages:\n');

      final List<String> violations = validateGeneratedFiles(
        lockfileBefore: lockfile,
        lockfileAfter: List<int>.of(lockfile),
        metadataContent: _validMetadata(
          'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        ),
      );

      expect(violations, isEmpty);
    });

    test('reports malformed generated inputs without throwing', () {
      final List<String> violations = validateGeneratedFiles(
        lockfileBefore: <int>[0xFF],
        lockfileAfter: <int>[0xFF],
        metadataContent: 'project_type: app\n',
      );

      expect(
        violations.map((String violation) => violation.split(' ').first),
        containsAll(<String>{
          '[GENERATED_LOCK_HEADER]',
          '[GENERATED_METADATA_CHANNEL]',
          '[GENERATED_METADATA_PLATFORMS]',
          '[GENERATED_METADATA_REVISION]',
          '[GENERATED_METADATA_UNMANAGED]',
        }),
      );
    });

    test('reports lockfile drift and an invalid platform revision', () {
      final List<String> violations = validateGeneratedFiles(
        lockfileBefore: utf8.encode('# Generated by pub\npackages:\n'),
        lockfileAfter: utf8.encode('# Generated by pub\npackages:\n  dio:\n'),
        metadataContent: _validMetadata(
          _revision,
        ).replaceFirst('base_revision: $_revision', 'base_revision: invalid'),
      );

      expect(
        violations.map((String violation) => violation.split(' ').first),
        containsAll(<String>{
          '[GENERATED_LOCK_STALE]',
          '[GENERATED_METADATA_PLATFORM_REVISION]',
        }),
      );
    });

    test('reports platform scope and unmanaged-file drift', () {
      final List<int> lockfile = utf8.encode('# Generated by pub\npackages:\n');
      final String metadata = _validMetadata(_revision)
          .replaceFirst('platform: ios', 'platform: web')
          .replaceFirst("    - 'ios/Runner.xcodeproj/project.pbxproj'\n", '');

      final List<String> violations = validateGeneratedFiles(
        lockfileBefore: lockfile,
        lockfileAfter: List<int>.of(lockfile),
        metadataContent: metadata,
      );

      expect(
        violations.map((String violation) => violation.split(' ').first),
        containsAll(<String>{
          '[GENERATED_METADATA_PLATFORMS]',
          '[GENERATED_METADATA_UNMANAGED]',
        }),
      );
    });
  });
}

String _validMetadata(String revision) {
  return '''
version:
  revision: "$revision"
  channel: "stable"

project_type: app

migration:
  platforms:
    - platform: root
      create_revision: $revision
      base_revision: $revision
    - platform: android
      create_revision: $revision
      base_revision: $revision
    - platform: ios
      create_revision: $revision
      base_revision: $revision

  unmanaged_files:
    - 'lib/main.dart'
    - 'ios/Runner.xcodeproj/project.pbxproj'
''';
}
